name: CI

on:
  push:
    branches:
      - Development
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install UV
        uses: astral-sh/setup-uv@v5

      - name: Install Dependencies
        run: |
          uv sync

      - name: Run tests
        run: |
          uv run pytest
